<?php require('template/head.phtml');?>
<div class="d-flex col-12 justify-content-center">
    <div class="card" style="width: 40rem; height: 50rem; margin-top: 3rem">
        <img src=<?php echo $view->profileImage; ?> class="card-img-top" style="height: 18rem; object-fit: cover" alt="profileImage">
        <div class="card-body">
            <div class="d-flex">
                <h1 class="card-title">@<?php echo $view->username; ?></h1>
                <button type="button" class="btn btn-primary text-end">Change</button>
            </div>
            <h3 class='card-subtitle text-muted'>Name</h3>
            <p class="card-text"><?php echo $view->fullName; ?></p>
            <h3 class='card-subtitle text-muted'>Email</h3>
            <p class="card-text"><?php echo $view->email; ?></p>
            <h3 class='card-subtitle text-muted'>Location</h3>
            <p><?php echo $view->position; ?></p>
            <div class="col-12 text-center">
            <?php require_once ('template/homeButton.phtml');?>
            </div>
        </div>
    </div>
</div>
<?php
require('template/footer.phtml');