<?php require('template/header.phtml');

$loggedIn = isset($_SESSION['loggedIn']);
$firstUsers = '{ "users": [';
foreach ($view->usersList as $user) {
    if ($loggedIn) {
        $friendship = $friendshipRepo->areFriends(["requesterId" => $_SESSION['username'], "addresseeId" => $user->getUsername()]);
        $user->setFriendship($friendship);
    }
    $firstUsers .= $user->toJson();
    if ($user != end($view->usersList)) {
        $firstUsers .= ", ";
    }
}
$firstUsers .= "]}";
?>

<div>
    <div class='d-flex justify-content-center align-items-center mt-1'><h2><?php echo $view->title;?></h2></div>
    <div style='margin-inline: 20vw;' class='row justify-content-center' id='usersContainer'>

    </div>
</div>
<div id="loader-wrapper">
    <h5 class="m-2" style="color: turquoise">Loading</h5>
    <span class="loader"><span class="loader-inner"></span></span>
</div>
<script type="text/javascript"  src="/js/ButtonManager.js"></script>
<script type="text/javascript"  src="/js/CardManager.js"></script>
<script type="text/javascript">
    let loader = document.getElementById("loader-wrapper");

    let currentPage = 0;

    let loggedUn = "<?php echo isset($_SESSION['loggedIn']) && $_SESSION['loggedIn'] == true? $_SESSION['username'] : "";?>";
    let btnManager = new ButtonManager(loggedUn);
    let cardManager = new CardManager(btnManager, loggedUn, document.getElementById("usersContainer"));
    cardManager.addUserCards(<?php echo $firstUsers; ?>.users);

    window.onscroll = function() {
        if (window.innerHeight + window.pageYOffset >= document.body.offsetHeight && !document.URL.includes("search")) {
            loadingAnimation();
            loadMoreUsers();
        }
    }

    function loadMoreUsers(){
        currentPage+=1;

        let users;

        let xhr = new XMLHttpRequest();
        xhr.open("GET", "../controllers/loadMoreUsers.php?page=" + currentPage + "&token="+ "<?php echo $_SESSION['token']?>" );

        xhr.onreadystatechange = function() {
            if (xhr.readyState == 4) {
                if (xhr.status == 200) {
                    loadingAnimation();
                    users = JSON.parse(xhr.responseText).users;
                    cardManager.addUserCards(users);
                } else {
                    console.log("Error: " + xhr.status);
                }
            }
        }

        xhr.send(null);
    }

    function loadingAnimation(){
        if(loader.style.opacity == 1){
            loader.style.opacity = 0;
        }else{
            loader.style.opacity = 1;
        }
    }


</script>
<?php
require('template/footer.phtml');