<?php require('template/head.phtml') ?>
<div class="signInContainer d-flex align-items-center justify-content-center">
    <div class="signingForm">
        <form action="<?php $_SERVER['PHP_SELF']; ?>" method="post">
            <div class="cl-12 text-center mt-5">
                <h2>Assignmet</h2>
            </div>
            <div class="mx-5">
                <div class="col-12 text-center">
                    <p style="color: red">
                        <?php
                            echo $view->validation;
                        ?>
                    </p>
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text" id="basic-addon1">@</span>
                    <input type="text" name="username" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" value="<?php if(isset($_POST['submit'])){echo $_POST['username'];} ?>">
                </div>
                <div class="mb-2">
                    <input type="password" name="password" class="form-control" placeholder="Password">
                </div>
                <div class="mb-3">
                    <?php
                    echo $view->staySignedIn;
                    ?>
                </div>
                <div class="mb-3">
                    <button type="submit" name="submit" class="btn form-control signInBtn">Sign In</button>
                </div>
                <div class="mb-5">
                <p>Don't have an account? <a href="../controllers/signUp.php" class="link-info">Sign up</a></p>
                </div>
                <div class="col-12 text-center">
                    <?php require_once ('template/homeButton.phtml');?>
                </div>
            </div>
        </form>
    </div>
</div>
<?php require('template/footer.phtml')?>
