<?php require('template/head.phtml') ?>
<div class="signInContainer d-flex align-items-center justify-content-center">
    <div class="signingForm">
        <form action="<?php $_SERVER['PHP_SELF']; ?>" method="post">
            <div class="cl-12 text-center mt-5">
                <h2>Assignmet</h2>
            </div>
            <div class="mx-5">
                <div class="col-12 text-center">
                    <p style="color: red">
                        <?php if($view->validation != null){
                            echo "$view->validation";
                        }else{
                            echo "<br>";
                        }
                        ?>
                    </p>
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text" id="basic-addon1">@</span>
                    <input type="text" name="username" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" value="<?php if(isset($_POST['submit'])){echo $_POST['username'];} ?>">
                </div>
                <div class="mb-2">
                    <input type="password" name="password" class="form-control" placeholder="Password">
                </div>
                <div class="mb-3">
                    <?php
                    echo $view->staySignedIn;
                    ?>
                </div>
                <div class="mb-3">
                    <button type="submit" name="submit" class="btn form-control signInBtn">Sign In</button>
                </div>
                <div class="mb-5">
                <p>Don't have an account? <a href="../controllers/signUp.php" class="link-info">Sign up</a></p>
                </div>
                <div class="col-12 text-center">
                    <a href="../controllers/index.php"><button type="button" class="btn backButton"><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                                <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                            </svg></button></a>
                </div>
            </div>
        </form>
    </div>
</div>
<?php require('template/footer.phtml')?>
