<div class="modal fade" id="changePassword" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Change Password</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="changePasswordForm" action="<?php echo $_SERVER["PHP_SELF"]?>" method="post">
                    <input class="form-control m-1" type="password" name="oldPassword" placeholder="Old Password">
                    <input class="form-control mx-1 mt-3"  type="password" name="newPassword" placeholder="New Password">
                    <input class="form-control mx-1"  type="password" name="newPassword2" placeholder="Repeat New Password">
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="Submit" form="changePasswordForm">Change <i class="bi bi-check-lg"></i></button>
            </div>
        </div>
    </div>
</div>