<div class="modal fade" id="changeProfileImage" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Change Profile Image</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="changeImageForm" action="<?php echo $_SERVER["PHP_SELF"]?>" method="post">
                    <label for="formFile" class="form-label">Upload Your New Profile Image</label>
                    <input class="form-control" type="file" name="image" accept="image/png, image/jpeg">
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="Submit" form="changeImageForm">Change</button>
            </div>
        </div>
    </div>
</div>