<div class="modal fade" id="cookiesModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Cookies & Privacy</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>This website uses cookies to ensure you get the best experience on our website.</p>
            </div>
            <div class="modal-footer">
                <a href=<?php echo $_SERVER['PHP_SELF'] . "?cookies=false";?>>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" >Do not Allow</button>
                </a>
                <a href=<?php echo $_SERVER['PHP_SELF'] . "?cookies=true";?>
                    <button type="button" class="btn btn-primary">Allow Cookies</button>
                </a>
            </div>
        </div>
    </div>
</div>