<?php require_once("head.phtml") ?>
<body role="document">
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand">
            <img src="../../images/wavingHand.png" alt="icon" width="30" height="30" class="d-inline-block align-text-top">Assignment</a>
        <form class="">
            <input class="form-control" id="searchBox" type="search" placeholder="Search" aria-label="Search">
        </form>
        <?php
            if($_SESSION['loggedIn'] == true){
                echo '
                    <div class="dropdown dropstart">
                      <button class="btn btn-secondary" type="button" id="account" data-bs-toggle="dropdown" aria-expanded="false"></button>
                      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="account">
                        <li><a class="dropdown-item active" href="#">Account</a></li>
                        <li><a class="dropdown-item" href="#">example</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="signOut.php">Sign out</a></li>
                      </ul>
                    </div>  
                ';
            } else{
                echo '
                    <a href="../../controllers/signIn.php">
                        <button class="btn signInBtn" type="button">Sign in</button>
                    </a>
                ';
            }
        ?>
    </div>
</nav>
</body>