<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="header" content="header">
    <meta name="Disuqi Hijazi" content="header">


    <!-- Bootstrap core CSS -->
<!--    <script type="javascript" src="js/bootstrap.js"></script>-->
<!--    <link href="../../css/bootstrap.css" rel="stylesheet">-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- My css files -->
    <link  href="../../css/my-style.css" rel="stylesheet">
    <!-- Icon -->
    <link   rel="icon" href="../../images/wavingHand.png">
    <title><?php echo $view->pageTitle; ?></title>
</head>
</html>