<?php require_once("head.phtml") ?>
<body role="document">
<div class="navbar navbar-dark bg-dark" style="position: fixed; width: 100%; top: 0px; z-index: 1" >
    <div class="d-flex col-12 flex-nowrap justify-content-between">
        <div class="p-2 col-4">
            <a class="navbar-brand" href="../../controllers/index.php"><img src="/images/wavingHand.png" alt="icon" width="30" height="30" class="d-inline-block align-text-top">Assignment</a>
            <?php
                echo '<a class="text-decoration-none fw-bold m-2 linker" href="../../controllers/index.php"><i class="bi bi-person-lines-fill"></i> Home</a>';
                if(isset($_SESSION['loggedIn'])){
                    echo '<a class="text-decoration-none fw-bold m-2 linker" href="../../controllers/index.php?search=friends"><i class="bi bi-heart-fill"></i> Friends</a>';
                    echo '<a class="text-decoration-none fw-bold m-2 linker" href="../../controllers/index.php?search=requests"><i class="bi bi-send-fill"></i> Requests</a>';
                    echo '<a class="text-decoration-none fw-bold m-2 linker"  href="../../controllers/index.php?search=declined"><i class="bi bi-slash-circle-fill"></i> Declined</a>';
                }
            ?>
        </div>
        <div class="p-2 col-2">
            <form action="../../controllers/index.php">
                <input class="form-control" id="searchBox" type="search"  name="search" placeholder="Search" aria-label="Search">
                <button style="display: none" type="submit"></button>
            </form>
        </div>
        <div class="col-4 text-end">
            <?php
                echo $view->signInBtn;
            ?>
        </div>
    </div>
</div>
</nav>
</body>