<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="header" content="header">
    <meta name="Disuqi Hijazi" content="header">


    <!-- Bootstrap core CSS -->
    <link href="../../css/bootstrap.css" rel="stylesheet">
    <!-- My css files -->
    <link  href="../../css/my-style.css" rel="stylesheet">
    <!-- Icon -->
    <link   rel="icon" href="../../images/wavingHand.png">
    <title><?php echo $view->pageTitle; ?></title>
</head>
</html>
<?php session_start();
if(!isset($_SESSION['loggedIn'])){
    $_SESSION['loggedIn'] = false;
}